export const WRITE_BLOG_POST = "WRITE_BLOG_POST";
export const BLOG_POSTED_SUCCESSFULLY = "BLOG_POSTED_SUCCESSFULLY";
export const POST_BLOG = "POST_BLOG";
export const SINGLE_BLOG_TO_DISPLAY = "SINGLE_BLOG_TO_DISPLAY";
export const SINGLE_MY_BLOG_TO_DISPLAY = "SINGLE_MY_BLOG_TO_DISPLAY";
export const DELETE_BLOG = "DELETE_BLOG";
export const UPDATE_BLOG = "UPDATE_BLOG";
